### PR TITLE
Update for a better "Current conditions" layout

### PR DESCRIPTION
**Pull request by MatsA**

### CODE REVIEW

**Comment by MatsA** [comment]
Nice you accept PR:s despite the distribution is in "limited future maintenance".
Thanks Mats !

**Comment by ktrue** [comment]
Thanks again, Mats!  I'm really looking to deprecate and archive this release in the future.  I think that Wim Van der Kuil's pwsdashboard is the much improved version and is actively maintained.

**Comment by MatsA** [comment]
Hi ! Fully understand that you want to archive this release and recommend Wim:s version which I probably will turn to when this applications stops to work. The thing with this application is that the GUI is really nice and the best I have seen for a weather application. Mats

**Comment by ktrue** [comment]
It may have a very pleasing/pretty front end, but the back-side is not at all 'pretty' nor easy to maintain (as well you know).
Wim's pwsdashboard has a very similar one-page presentation, and it's back-side is very much better structured, maintained and supports more weather stations and features.  I'm just fatigued by trying to maintain this version and am only updating when absolutely necessary.  Thanks for your efforts to keep it alive, I'll continue to accept pull requests for your updates.

**Pull request merged**
